### ISSUE TITLE
Decimals, 

### ISSUE THREAD

**Issue by dirkjf** [DamienHarper/DoctrineAuditBundle#106]
When I have any decimal type in my entity, upon updating the entity a new audit record is saved in which it seems the value was changed. This is even the case when I set the scale in my form to 1. For example, if I have a number saved as 5.0 in my database, when I edit the entity and do not touch this number, for this value "{"old":"5.0","new":"5"}" is saved. 

I am using MariaDB version 10.3.15 on an Apache server 2.4.39 with PHP 7.3.6. 

My entity field looks like this: 

```
/**
* @ORM\Column(type="decimal", precision=3, scale=1, nullable=true)
*/
private $credits;
```

Thanks!

**Comment by DamienHarper** [comment]
@dirkjf thanks for the report. I’ll have a look at it asap.

**Comment by DamienHarper** [comment]
@dirkjf Could you please test again `master` branch and provide me some feedback?

**Comment by dirkjf** [comment]
Tested it again, but I still have the same issue. Every time I update for all decimal values: {"old":"5.0","new":5}. And although it may show only "5" in the form, the actual data that is stored is "5.0".

**Comment by dirkjf** [comment]
BTW, also when in my form I type "5.0", I get the same {"old":"5.0","new":5}.

**Comment by dirkjf** [comment]
I ran some more tests. What helps (FOR ME) is to type cast the value to a float. So when I use on line 160 of AuditHelper.php: `$convertedValue = (float) $type->convertToPHPValue($value, $platform);` it works as I would expect. I don't know if this could be problematic for other users.

**Comment by DamienHarper** [comment]
@dirkjf ok but bothers me is that on `master`, decimals are process as you describe (since my last changes): https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/src/DoctrineAuditBundle/Helper/AuditHelper.php

**Comment by dirkjf** [comment]
I understand. Maybe [this](https://stackoverflow.com/questions/40531133/decimal-return-string-in-doctrine) is why?

**Comment by DamienHarper** [comment]
I close this issue as this is more a Doctrine one.
