### ISSUE TITLE
Drop + Create Indexes everytime schema update is executed

### ISSUE THREAD

**Issue by n3o77** [DamienHarper/DoctrineAuditBundle#110]
Hi @DamienHarper 

I noticed another weird bug, not critical but weird. Every time when I execute `doctrine:schema:update --force` it will drop all audit indexes and create them again.

SF3.4 
10.1.38-MariaDB-0+deb9u1

`./bin/console doctrine:schema:update --force --dump-sql`
```sql
     DROP INDEX object_id_922a2e2fde8c24f7943de9485a005b9f_idx ON country_audit;
     DROP INDEX discriminator_922a2e2fde8c24f7943de9485a005b9f_idx ON country_audit;
     DROP INDEX blame_id_922a2e2fde8c24f7943de9485a005b9f_idx ON country_audit;
     CREATE INDEX object_id_922a2e2fde8c24f7943de9485a005b9f_idx ON country_audit (object_id);
     CREATE INDEX discriminator_922a2e2fde8c24f7943de9485a005b9f_idx ON country_audit (discriminator);
     CREATE INDEX blame_id_922a2e2fde8c24f7943de9485a005b9f_idx ON country_audit (blame_id);
     DROP INDEX object_id_044baacb2e72a0e8016709888314abd2_idx ON charge_audit;
     DROP INDEX discriminator_044baacb2e72a0e8016709888314abd2_idx ON charge_audit;
     DROP INDEX blame_id_044baacb2e72a0e8016709888314abd2_idx ON charge_audit;
     CREATE INDEX object_id_044baacb2e72a0e8016709888314abd2_idx ON charge_audit (object_id);
     CREATE INDEX discriminator_044baacb2e72a0e8016709888314abd2_idx ON charge_audit (discriminator);
     CREATE INDEX blame_id_044baacb2e72a0e8016709888314abd2_idx ON charge_audit (blame_id);
```

**Comment by DamienHarper** [comment]
@n3o77 Thanks for the report, does this only happen on specific tables (country and charge in your example) ? or does this happen on every table ? or does this happen on random tables ?

Could you please post entities this happens on?

**Comment by n3o77** [comment]
happens on every table

**Comment by DamienHarper** [comment]
@n3o77 It looks like you're not alone, the problem seems to be Doctrine related. Did you try to set `server_version` in your doctrine configuration?
- https://github.com/doctrine/orm/issues/6790
- https://symfony.com/doc/current/reference/configuration/doctrine.html

**Comment by n3o77** [comment]
Looks like it. Will do some tests later today, thank you

**Comment by DamienHarper** [comment]
@n3o77 any news?

**Comment by n3o77** [comment]
Sorry, didn't have time to test this yet on a maria-db server. But i don't have the problems on mysql so i'd say we can close this issue. If that's not the problem we can reopen it.

**Comment by RomanApunts** [comment]
Hello,

Today i had the same problem but without drop statements...

My environment is different if that help:

Symfony 5.3.2
SQL SERVER 15.0
Windows

I tried to tell doctrine server_version without success...

------------------------------------------------------
php bin/console audit:schema:update --dump-sql

 The following SQL statements will be executed:

     ALTER TABLE company_log ALTER COLUMN id INT IDENTITY NOT NULL;
     ALTER TABLE maquina_log ALTER COLUMN id INT IDENTITY NOT NULL;
     ALTER TABLE opportunity_log ALTER COLUMN id INT IDENTITY NOT NULL;
     ALTER TABLE usuarios_log ALTER COLUMN id INT IDENTITY NOT NULL;
