### ISSUE TITLE
Metadata early initialization 

### ISSUE THREAD

**Issue by versh23** [DamienHarper/DoctrineAuditBundle#116]
Helllo!

here https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/src/DoctrineAuditBundle/AuditConfiguration.php#L114

Metadata initialization very early and its break my loadClassMetadata listener, because there are no listernes in eventManager at this moment and metadata initialized once..

what about change direct access to AuditConfiguration::$entities and use AuditConfiguration::getEntities() everywhere and make update entities list by annotation loader once here?

or may be make service are lazy but lazy params dont work in my hands:(

what do you think ?

**Comment by versh23** [comment]
#117 one of possible solution

**Comment by DamienHarper** [comment]
I close this issue since #117 has been merged.
