### ISSUE TITLE
Problem setting up secondary database

### ISSUE THREAD

**Issue by jeffesonmaia** [DamienHarper/DoctrineAuditBundle#118]
When adding the `storage_entity_manager` option symfony returns the following error

`Unrecognized option" storage_entity_manager "under" dh_doctrine_audit`

**Comment by DamienHarper** [comment]
Hi @jeffesonmaia, this option is only available in version 3.0.0 (released today), is this the version you are using? you can check which version you are using with the following command `composer show | grep "doctrine-audit-bundle"`. Also, did you try to clear your cache?

**Comment by DamienHarper** [comment]
@jeffesonmaia are you still facing the issue?

**Comment by jeffesonmaia** [comment]
Thanks, for the support! The problem was the version.
