### ISSUE TITLE
Hi, command audit:clean not work.

### ISSUE THREAD

**Issue by jodeca** [DamienHarper/DoctrineAuditBundle#119]
I use version 3. When I execute the "audit: clean" command, it does not delete the data from the audit tables.

Please, your support.

Note: Sorry for my bad English. I use Symfony 4.3.

**Comment by DamienHarper** [comment]
Hi @jodeca! Thanks for the report, I’ll have a look at it ASAP

**Comment by jodeca** [comment]
Is it possible that the ID of the records is uuid? or at least we can define the type (integer or uuid) of value that the ID can contain.

Thank you.

**Comment by DamienHarper** [comment]
@jodeca the command works in my tests. 
By default, with no argument, this command keeps the last 12 months of data => are you sure you had data older than 12 months? Can you post the command the you run?

**Comment by jodeca** [comment]
Hi @DamienHarper, the command y data: 

- php bin/console audit:clean
- create_at => '2019-11-03 22:15:55'

Thanks

**Comment by DamienHarper** [comment]
@jodeca thanks for the feedback, but everything seems ok to me: audit data is dated `2019-11-03 22:15:55` and you ran `bin/console audit:clean` => this command will keep 12 months of audit data (it will try to delete anything older than 12 months before the day you run it)

As an example, let's say you run that command on `2019-11-03` it will (try to) delete anything before `2018-11-03`.

**Comment by jodeca** [comment]
Hi, you are right. I was wrong.

Thank you.

Sorry for the inconvenience.
