### ISSUE TITLE
Is tracking of entry deletion planned in future?

### ISSUE THREAD

**Issue by mrvnklm** [DamienHarper/DoctrineAuditBundle#12]
As the readme says its the bundle is not tracking the deletion of entries, is this going to take place in the future?
Whats the reason why its not a feature?

**Comment by DamienHarper** [comment]
@mrvnklm Do you mean tracking deletion through direct SQL queries?

**Comment by DamienHarper** [comment]
It should bee tracked, can you provide me an example where it doesn't work?

**Comment by mrvnklm** [comment]
Issue was caused by using softdeleteable. Thanks and sorry @DamienHarper

**Comment by mrvnklm** [comment]
@DamienHarper would it be possible to implement a softdeleteable delete action? So if deletedAt is set, its also handled as deleted

**Comment by DamienHarper** [comment]
The main purpose of the bundle is to track SQL statements (INSERT, UPDATE, DELETE). It doesn't  interpret them.
A soft delete is an UPDATE statement of a field used to mark a record as deleted without removing it from the database. Soft deletes can be handled by several ways, the most common one is to use a dedicated Doctrine extension, but it's not the only one. 
So soft deleted records can be tracked with a boolean flag, a deletion timestamp, etc depending on the Doctrine extension/application logic.
It would be hard to support any kind of soft delete implementation but I'll think about it.
