### ISSUE TITLE
Losing Audit Data

### ISSUE THREAD

**Issue by kxc4182** [DamienHarper/DoctrineAuditBundle#120]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.0.0
| PHP version                 | 7.2.12
| Database                    | MySQL

#### Summary

I just upgraded to DoctrineAuditBundle v3.0.0 from v2.3.1 and I haven't changed any configuration.
I'm also only using one entity manager for everything.

I tried testing a simple insertion and I'm not getting any audit data persisted after the onFlush event.
Doing some investigation by setting up breakpoints, I think the bug is in the **onFlush** method of **DoctrineSubscriber**.

```
public function onFlush(OnFlushEventArgs $args): void
{
    $em = $args->getEntityManager();
    $transaction = new AuditTransaction($this->manager->getHelper());
    ...
    // Populate transaction
    $transaction->collect();
}
```
The EntityManager **$em** which is passed by the parameter of the callback correctly contains the unit of work which has the entity to be inserted in the table, but inspecting the EntityManager via **$transaction->getEntityManager()** shows an empty unit of work and therefore nothing to be audited.
A snapshot of the two different EntityManager instances right after **$transaction** is initialized.
![image](https://user-images.githubusercontent.com/6570313/68247111-1fa65200-ffe8-11e9-9964-352c9d82cd19.png)
![image](https://user-images.githubusercontent.com/6570313/68247150-3056c800-ffe8-11e9-9a09-ea96ac3274fa.png)

Then in the following code block, **$uow->getScheduledEntityInsertions()** returns an empty array and we don't collect any changes.
```
/**
 * @param UnitOfWork $uow
 */
public function collectScheduledInsertions(UnitOfWork $uow): void
{
    foreach ($uow->getScheduledEntityInsertions() as $entity) {
        if ($this->configuration->isAudited($entity)) {
            $this->inserted[] = [
                $entity,
                $uow->getEntityChangeSet($entity),
            ];
        }
    }
}
```
Any ideas? Thanks

**Comment by DamienHarper** [comment]
Hi @kxc4182, thanks for this detailed report. This is weird, I have to investigate and try to reproduce the issue. Is this 100% reproducible on your side?

Could you please also post the result of `composer show`?

**Comment by kxc4182** [comment]
I just tried again and upgraded to 3.0.0 and I don't have the issue anymore.
It was probably a problem with dependencies before as you are suggesting with the composer show.
Unfortunately, I didn't save a snapshot of this when I initially found the issue.

**Comment by DamienHarper** [comment]
@kxc4182 glad to hear that you solved the problem yourself, so I close this issue.

**Comment by dtraore** [comment]
Hello! I just install the bundle,

I'm on symfony 4.2

this is my configuration file:

```
dh_doctrine_audit:
    table_prefix: 'audit_'
    table_suffix: ''
    timezone: 'Europe/Paris'
    enabled: true
    entities:
        AppCore\Entity\MyEntity: ~
```

the schema update commande work fine
`bin/console doctrine:schema:update --force`

But when I edit or add content, no operation saved, to debug I did dump in the onFlush()

this is where I did dump 

```
public function onFlush(OnFlushEventArgs $args): void
    {
        $em = $args->getEntityManager();
        $transaction = new AuditTransaction($this->manager->getHelper());

        dump($em, $transaction->getEntityManager(), __METHOD__);
```

Here the results of dump 

![image](https://user-images.githubusercontent.com/7816604/69902153-62124300-138a-11ea-8003-2c42a06b201d.png)

![image](https://user-images.githubusercontent.com/7816604/69902160-82da9880-138a-11ea-8297-c1c09df6119f.png)


Two unitOfWork are different.

Thanks in advance.

**Comment by DamienHarper** [comment]
@dtraore Thanks for the report, could you please open a dedicated issue? Also, could you post or explain what you do when you say _"[...]when I edit or add content, no operation saved[...]"_

**Comment by dtraore** [comment]
OK @DamienHarper
