### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by Herz3h** [DamienHarper/DoctrineAuditBundle#123]
I've tried this bundle, it works pretty well with the annotation addition. However there are not many functions to retrieve data from database. 

In my specific situation I would like to retrieve all the ASSOCIATE + DISSOCIATE events for an entity, but the setFilter seems to support only one filter at a time. 

So as a workaround, I'd use DQL (or SQL probably... Not sure if it's possible to use DQL here) to retrieve the data directly. But then, does the database structure change often (My code might break then...)

Thanks

**Comment by DamienHarper** [comment]
@Herz3h thanks for the suggestion. I'll add that feature in a next release.

**Comment by DamienHarper** [comment]
Regarding database structure change, it does not happen frequently. Most of the time, it consists of adding new columns so your code should not break ;)

**Comment by Herz3h** [comment]
Ok good, finally I have decided to retrieve all events without any filter until the feature is available.

**Comment by DamienHarper** [comment]
@Herz3h PR#123 should address your request about filtering using several filters at once: you can now use `$reader->filterBy([AuditReader::ASSOCIATE, AuditReader::DISSOCIATE])`

**Comment by DamienHarper** [comment]
3.1.0 is released

**Comment by Herz3h** [comment]
Awesome, thank you !
