### ISSUE TITLE
After upgrading to doctrine-bundle 2.0 - dependency injection missed type hint

### ISSUE THREAD

**Issue by yspef** [DamienHarper/DoctrineAuditBundle#124]
during my last composer update command, the doctrine-bundle changed to 2.0

 - Removing doctrine/doctrine-cache-bundle (1.3.5)
  - Updating doctrine/doctrine-bundle (1.11.2 => 2.0.0): Loading from cache
  - Updating doctrine/orm (v2.6.4 => v2.7.0): Loading from cache

From this moment on, I got the error :

!!  In TwigExtension.php line 30:
!!                                                                                 
!!    Argument 1 passed to DH\DoctrineAuditBundle\Twig\Extension\TwigExtension::_  
!!    _construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterfa  
!!    ce, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /h  
!!    ome/facundo/proyectos/dfm/var/cache/dev/ContainerGp43PcT/srcApp_KernelDevDe  
!!    bugContainer.php on line 1068                                                
!!                                                                                 
!!  

I found a workaround by defining manually the twig extension service as : 

    dh_doctrine_audit.twig_extension:
        class: 'DH\DoctrineAuditBundle\Twig\Extension'
        arguments:
            - '@DH\DoctrineAuditBundle\Twig\Extension\RegistryInterface'

I think this is not the best solution, but in the meantime I can run the web.

Regards.
Facundo.

pd.  I use Symfony 4

**Comment by DamienHarper** [comment]
Hi @yspef, I'm a bit confused, what version of this bundle are you using? You can run `composer show | grep "doctrine-audit-bundle"` and report it back here.

I strongly encourage you to upgrade to the latest version of the audit bundle (cf. [How to upgrade?](https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/CHANGELOG.md#how-to-upgrade))

**Comment by maxhelias** [comment]
RegistryInterface & Registry are marked deprecate since DoctrineBundle 1.12 (doctrine/DoctrineBundle#1052) and already remove in 2.0.
You must use ManagerRegistry to get doctrine on 2.0

**Comment by DamienHarper** [comment]
@yspef @maxhelias This should be fixed on `master` branch.

**Comment by yspef** [comment]
> composer show | grep "doctrine-audit-bundle"

It gives :

damienharper/doctrine-audit-bundle  3.0.0      This bundle creates audit logs for all doctrine ORM database related changes.

**Comment by yspef** [comment]
> @yspef @maxhelias This should be fixed on `master` branch.

Upgraded to dev-master solves the issue.
Thanks.
Regards.

**Comment by YetiCGN** [comment]
I am experiencing the same problem. Can you release this as 3.0.1, please?

**Comment by DamienHarper** [comment]
@YetiCGN I will make a new release soon

**Comment by YetiCGN** [comment]
Thanks, that's great!

**Comment by webmasterMeyers** [comment]
I just had the same issue, but realised I was on `^2.0`, updating to `^3.0` worked
