### ISSUE TITLE
GEDMO Tree Extensions + Doctrine Entity Inheritance

### ISSUE THREAD

**Issue by Herz3h** [DamienHarper/DoctrineAuditBundle#128]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.0.0
| PHP version                 | 7.1.31
| Database                    | MySQL
| Symfony | 3.4.32
#### Summary

Just enabling the DHDoctrineAuditBundle (no WhiteOctoberPagerfantaBundle), the tree extension doesn't return node that have relations with entities making use of doctrine inheritance.

#### Current behavior

All my entities have the @Audit\Auditable annotation, I ran the migration. Added routes to routing.yml for the controller. I'm using the [GEDMO Tree Extension](https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md). And fetching the node hierarchy starting from the root element (this code didn't change after the audit bundle install, and was returning complete results.) Only nodes linking to entities that make use of Doctrine Inheritance don't show up.

#### How to reproduce

Install tree extensions, build a tree that links an entity that's making use of doctrine inheritance. Here is what my parent entity has:

```php
/**
 * ContactMaster
 *
 * @ORM\Table(name="f_contact_master")
 * @ORM\Entity(repositoryClass="MyBundle\Repository\ContactMasterRepository")
 * @Audit\Auditable
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="cont_mast_type", type="string", length=255)
 * @ORM\DiscriminatorMap({
 *     "constactMaster"="ContactMaster",
 *     "contact" = "Contact",
 *     "professionnelDroit" = "ProfessionnelDroit",
 *     "juridiction" = "Juridiction"
 * })
 * @ORM\HasLifecycleCallbacks()
 */
class ContactMaster
{
}
````

So the tree nodes that link to any of Contact/ProfessionnelDroit/Juridiction entity dont appear in my tree. 

I have tried removing the Auditable annotation from this ContactMaster entity and TreeEntity aswell, it makes no difference.

#### Expected behavior

Every entity should be loaded. 

> Where should I be looking for anything related to entity fetching in this bundle ? Is there an EventListener that's changing the results ? 

Let me know if you need more details.

**Comment by DamienHarper** [comment]
@Herz3h thanks for the report, I'll have a look asap

**Comment by DamienHarper** [comment]
@Herz3h can you try against event-subscriber-priority branch?
composer require damienharper/doctrine-audit-bundle "dev-event-subscriber-priority"

**Comment by DamienHarper** [comment]
@Herz3h did you had a chance to test `event-subscriber-priority` branch?

**Comment by Herz3h** [comment]
@DamienHarper Sorry not yet, will try it at work tomorrow and give feedback here ;)

**Comment by Herz3h** [comment]
I have an issue while trying to install that version.

```
 Problem 1
    - Can only install one of: doctrine/orm[v2.7.0, v2.6.6].
    - Can only install one of: doctrine/orm[v2.7.0, v2.6.6].
    - Can only install one of: doctrine/orm[v2.7.0, v2.6.6].
    - damienharper/doctrine-audit-bundle dev-event-subscriber-priority requires doctrine/orm ^2.7 -> satisfiable by doctrine/orm[v2.7.0].
    - Installation request for damienharper/doctrine-audit-bundle dev-event-subscriber-priority -> satisfiable by damienharper/doctrine-audit-bundle[dev-event-subscriber-priority].
    - Installation request for doctrine/orm (locked at v2.6.6, required as ^2.6) -> satisfiable by doctrine/orm[v2.6.6].
```
I previously had doctrine/orm 2.5, I upgraded to 2.6.6 and stil same issue. I'm trying v2.7.0 now..

**Comment by DamienHarper** [comment]
@Herz3h OK, I have to investigate more

**Comment by DamienHarper** [comment]
@Herz3h could you please provide me a sample project that reproduces the issue please? It would be very helpful.

**Comment by Herz3h** [comment]
I'm currently having the problem on an application I can't really share the source code with anyone (company app)... Is there a specific file where the compatibility with GEDMO extensions is handled so I could take a look perhaps ?

**Comment by DamienHarper** [comment]
I fully understand that you can't share the entire app but could you for example extract the classes (entities) composing your tree (strip your business/private stuff from them) and the instructions that populate and persist the tree (instructions which trigger the issue) so that I can start with a concrete reproducible use case?

**Comment by Herz3h** [comment]
I finally upgraded to Symfony 4.4.7 and AuditBundle 3.4 (before I had AuditBundle 3.0.0 and sf 3.4) and this seems to work on this version instead.
