### ISSUE TITLE
Release 3.0.0 breaks on Symfony 4.4

### ISSUE THREAD

**Issue by ThomasTr** [DamienHarper/DoctrineAuditBundle#129]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.0.0
| PHP version                 | 7.3.11

#### Summary

Actual realeased version 3.0.0 breaks when upgrade to Symfony 4.4 because of already fixed [RegistryInterface deprecation](https://github.com/DamienHarper/DoctrineAuditBundle/commit/4d0568d032a104b0b221d0d3a24393d5fe259dbe)

Please be so kind as to publish a new release for it. 
Thank you very much for your great bundle.

Thomas

**Comment by DamienHarper** [comment]
@ThomasTr it's already fixed and a new release will be done shortly. In the meantime, you can use `master` branch.

**Comment by DamienHarper** [comment]
Duplicate of #124

**Comment by DamienHarper** [comment]
3.1.0 is released

**Comment by ThomasTr** [comment]
Thank you very much
