### ISSUE TITLE
Hi, error when install package 'DoctrineAuditBundle' in symfony 5

### ISSUE THREAD

**Issue by jodeca** [DamienHarper/DoctrineAuditBundle#131]
I use Symfony 5 and when install package, return error. I attach imagen.

Thanks
![image](https://user-images.githubusercontent.com/4274107/69891227-e8665080-12c8-11ea-88a1-7c5298d83e8c.png)

**Comment by DamienHarper** [comment]
@jodeca The bundle is not yet compatible with Symfony 5. I'm working on it and I'll release a new version in a few days.

**Comment by jodeca** [comment]
Thanks @DamienHarper. :)

**Comment by DamienHarper** [comment]
@jodeca could you please try against `master` branch?

**Comment by jodeca** [comment]
Hi, @DamienHarper, I test and all ok. Thanks for your support.

**Comment by DamienHarper** [comment]
@jodeca thanks for the feedback

**Comment by DamienHarper** [comment]
@jodeca 3.2.1 is live with symfony 5 support

**Comment by jodeca** [comment]
it's great. Thank you very much.
