### ISSUE TITLE
Conflict version of twig/twig in composer.json file

### ISSUE THREAD

**Issue by Phibus** [DamienHarper/DoctrineAuditBundle#132]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 2.5.0
| PHP version                 | 7.2.14
| Database                    | MySQL

#### Summary
The conflict version of twig/twig seems to be incorrect in the composer.json file.

#### Current behavior
Composer return an error due to a conflict with twig/twig if you try to install the bundle with a version of twig/twig higher or equal than the 1.40.

#### How to reproduce

Create a new folder for the test
composer require "twig/twig:^1.0"
composer require "damienharper/doctrine-audit-bundle:^2.5"

The CLI return :
![ConEmu64_kDYcKfhJLl](https://user-images.githubusercontent.com/24300667/69898887-59f0de00-135f-11ea-886c-4b60ce2ba77a.png)

#### Expected behavior

The bundle should be installed successfully if the version of twig is higher or equal than the 1.40.
Put the conflict version of twig/twig to "<1.40|<2.9,>=2.0" should solve the problem.

I just tried for the 2.5 version of the bundle.
The behavior is maybe the same for the 3.x.

**Comment by DamienHarper** [comment]
@Phibus Thanks for the feedback, I'll have a look at it ASAP.

**Comment by DamienHarper** [comment]
Also, could you please try with the latest version of the bundle?

**Comment by DamienHarper** [comment]
@Phibus could you post your `composer.json` (at least the `require` section) to ease debugging please?

**Comment by Phibus** [comment]
Hello @DamienHarper.
You can find the `composer.json` I used below.
```json
{
    "require": {
        "twig/twig": "^1.0",
        "damienharper/doctrine-audit-bundle": "^2.5"
    }
}
```

The composer's version used is the 1.9.1.

**Comment by DamienHarper** [comment]
@Phibus could you try `updated-twig-deps` branch?

**Comment by DamienHarper** [comment]
@Phibus do you still experiment the issue with `master` branch since twig des have been updated?

**Comment by DamienHarper** [comment]
@Phibus I close this issue as it hasn't received feedback recently. Feel free to reopen it if needed.
