### ISSUE TITLE
Please don't change paths / namespaces in patches

### ISSUE THREAD

**Issue by n3o77** [DamienHarper/DoctrineAuditBundle#142]
Hi @DamienHarper thanks again for putting so much work into this bundle.

I just upgraded a few projects from 3.2.1 to 3.2.2 and a lot of our templates broke because the helper paths were changed, which wasn't expected in a patch version change as these should be BC. Also a mention in the change log would be awesome so in the future it's not necessary to manually check everything. Unfortunately there are some project which aren't fully covered by tests.

**Comment by DamienHarper** [comment]
@n3o77 I'm sorry for the inconvenience, you're right these changed should have been postponed to next major. I used to add a mention in the changelog which I forgot to do in latest release. 
I'll update the changelog ASAP.

**Comment by n3o77** [comment]
Thanks you so much. I think a good solution would be to still have the old file which includes / extends the new one and throws an deprecation notice.
