### ISSUE TITLE
Let the cleanup command accept an ISO 8601 duration

### ISSUE THREAD

**Issue by patrickmatsumura** [DamienHarper/DoctrineAuditBundle#144]
It would be very handy for the cleanup command to [also] accept an ISO 8601 duration ([https://en.wikipedia.org/wiki/ISO_8601#Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)) as `keep` parameter, e.g. `P7D` to only delete records that are older than 7 days. Being able to define an arbitrary duration could be quite useful.

I could work on this if you want. Just let me know.

**Comment by DamienHarper** [comment]
@patrickmatsumura thanks for the suggestion, it might be useful for some. To be honest, I haven't planned such feature soon so if you want to contribute, feel free to submit a PR, it will be much appreciated ;)

**Comment by patrickmatsumura** [comment]
Ok. I have a client that has very strict retention policies. Monthly intervals would not fit their requirement and must have a at least daily precision. :)

Would you rather have a new parameter or would you like to keep `keep`? I think keeping `keep` and still allowing numerical values should result in the subtraction of months, as it does now. If the value is a string starting with the capital letter P, it should be interpreted as `DateInterval`. That way we wouldn't break things for existing users. What do you think?

**Comment by DamienHarper** [comment]
@patrickmatsumura I also think that `ISO-8601` is more flexible than the actual solution and should replace it in the future (next major version). I also would like to keep `keep` argument and allow it to receive both numerical and string values to avoid BC break. Then:
- If a numerical value is provided, it should behave as it behaves now: drop data older than number of month provided from today **and trigger a deprecation warning**
- If a string value is provided, it must match a `DateInterval` pattern describing the period of retention (if `P7D` is provided, it means we drop data older than 7 days from now -- we keep the last 7 days of data)

**Comment by DamienHarper** [comment]
@patrickmatsumura are you still working on this? do you need some help?

**Comment by patrickmatsumura** [comment]
Yes, I am. I just have some other things on my plate right now and the upcoming holidays and some deadlines are keeping me busy. I should have a PR by the end of the week though.

**Comment by DamienHarper** [comment]
@patrickmatsumura Any progress on this?

**Comment by DamienHarper** [comment]
@patrickmatsumura feel free to submit your PR even unfinished, I'll look into it

**Comment by patrickmatsumura** [comment]
I had personal things going on over the holidays and I had to support my wife with the kids. I’ll be working on this and have a PR by the end of the week.

**Comment by DamienHarper** [comment]
@patrickmatsumura thanks for the update! I hope everything's fine/back to normal on your personal side though

**Comment by patrickmatsumura** [comment]
Added PR #170 

> I hope everything's fine/back to normal on your personal side though
It was nothing serious. Just some things that kept me busy. 😊

**Comment by DamienHarper** [comment]
I merged your PR so I can close this issue. Thanks @patrickmatsumura!

**Comment by patrickmatsumura** [comment]
You‘re welcome and thank you for this bundle.
