### ISSUE TITLE
An exception occurred while executing 'SELECT COUNT(id) FROM tablename at WHERE (object_id = ?) AND (type IN (?))' with params [1, ["update"]]:  Notice: Array to string conversion

### ISSUE THREAD

**Issue by gam6itko** [DamienHarper/DoctrineAuditBundle#150]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.2.3
| PHP version                 |  7.2
| Database                    | MySQL 5.7
|doctrine/dbal      |                      v2.10.0  
| doctrine/orm  |                           v2.7.0  

#### Summary

I think `$filters` property should be removed from `AuditReader`. It should be passed in the method args

#### Current behavior

An exception occurred while executing 'SELECT COUNT(id) FROM tablename at WHERE (object_id = ?) AND (type IN (?))' with params [1, ["update"]]:  Notice: Array to string conversion

#### How to reproduce

```php
// somwhere  in project before controller action call
$audits = $this->auditReader
           ->filterBy(AuditReader::UPDATE)
           ->getAudits(SettlementService::class, $ss->getId());
// in controller
$pager = $this->auditReader->getAuditsPager(SettlementService::class, 1, 1, AuditReader::PAGE_SIZE);
```

#### Expected behavior

No exception

**Comment by gam6itko** [comment]
Looks like here is the problem
https://github.com/DamienHarper/DoctrineAuditBundle/blob/15f778dec96f161a2bc1ff1c81f987a80c3aa950/src/DoctrineAuditBundle/Reader/Paginator.php#L65

**Comment by DamienHarper** [comment]
@gam6itko I will look at it ASAP

**Comment by DamienHarper** [comment]
@gam6itko could you please test against `fix-150` branch?
`composer require damien harper/doctrine-audit-bundle "dev-fix-150"`

**Comment by DamienHarper** [comment]
@gam6itko This should be fixed in `master` branch. Could you please test it and provide me some feedback?

**Comment by gam6itko** [comment]
@DamienHarper I'll do it ASAP

**Comment by gam6itko** [comment]
@DamienHarper the problem has gone. You can close the issue
