### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by cnizzardini** [DamienHarper/DoctrineAuditBundle#160]
Doctrine has support for Mongodb through its ODM, has this project been tested with MongoDb at all? Any reasons it wouldn't work?

**Comment by DamienHarper** [comment]
Hi @cnizzardini! Unfortunately, this bundle has not been tested with MondoDb and can't work out of the box with MongoDb as it's been thought and designed for Doctrine ORM, not Doctrine ODM.

**Comment by cnizzardini** [comment]
Can you spitball an estimate on how long you think it would take for someone to fork and add support for this? Do you think the code is extendable, or would it be a considerable amount of work?
