### ISSUE TITLE
Entity ID lost in pagination

### ISSUE THREAD

**Issue by MylesKingsnorth01** [DamienHarper/DoctrineAuditBundle#165]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.2.3
| PHP version                 | 7.3.4
| Database                    | MySQL

#### Summary

When viewing audits for an entity with an ID, navigating using the pager fanata pagination at the bottom removes the entity ID.

#### Current behavior

Lose entity ID on page navigate.

#### How to reproduce

View audits for an entity with an ID and navigate to page 2 etc.

#### Expected behavior

For it to navigate to then next page while maintaining the entity ID:

From: `/audit/App-Entity-MyEntity/342`
To: `/audit/App%5CEntity%5CMyEntity?page=2`

Expected: `/audit/App-Entity-MyEntity/342?page=2`

**Comment by DamienHarper** [comment]
Hi @MylesKingsnorth01 
It's already fixed in `master` branch (see #162)

**Comment by MylesKingsnorth01** [comment]
> Hi @MylesKingsnorth01
> It's already fixed in `master` branch (see #162)

When will the fix be tagged as a release?

**Comment by DamienHarper** [comment]
Hi @MylesKingsnorth01, I'll publish next release soon (today evening or tomorrow)

**Comment by DamienHarper** [comment]
@MylesKingsnorth01 3.3.0 is released
