### ISSUE TITLE
Boolean set to NULL instead of false

### ISSUE THREAD

**Issue by bhyassine** [DamienHarper/DoctrineAuditBundle#166]
Hello everyone,
When I am tracking changes on my Entities, I noticed that boolean set to false are being shown as set to Null...
I made some verification and I noticed that the false values are sent as "empty" to the twig file...
However, on the audit table, the values are correctly set as "false".
I think the problem come from the reader where may be it don't make a difference between false and null (there might be a missed strict comparison somewhere), but I couldn't find where it happen exactly!
Any clue?
PS: True values are set as "1", I wouldn't mind that it shows as "True"

Thanks a lot!

**Comment by DamienHarper** [comment]
@bhyassine thanks for the report, I'll have a look at this asap

**Comment by bhyassine** [comment]
It works perfectly well! Thanks a lot :-)

**Comment by DamienHarper** [comment]
@bhyassine 3.3.0 is released
