### ISSUE TITLE
why DH\DoctrineAuditBundle\User\UserInterface::getId() must return int|string|null?

### ISSUE THREAD

**Issue by calvera** [DamienHarper/DoctrineAuditBundle#169]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.3.2
| PHP version                 | 7.4
| Database                    | PostgreSQL

#### Summary

i use phpstan for static analysis, it reports this
``` 
/app/src/Entity/AbstractUser.php:207:Return type (Ramsey\Uuid\UuidInterface) of method App\Entity\AbstractUser::getId() should be compatible with return type (int|string|null) of method DH\DoctrineAuditBundle\User\UserInterface::getId()
```

#### How to reproduce

    /**
     * @return UuidInterface
     */
    public function getId(): UuidInterface
    {
        return $this->id;
    }

#### Expected behavior

i would expect i can use uuid as primary key

**Comment by patrickmatsumura** [comment]
You could return a string instead of the instance.

**Comment by DamienHarper** [comment]
@calvera at the moment, [UserInterface](https://github.com/DamienHarper/DoctrineAuditBundle/blob/e72b52106c6903d60595dd5266c4d261863d2303/src/DoctrineAuditBundle/User/UserInterface.php#L10) do not have any real return typehint for the `UserInterface::getId()` method, they are only suggested thanks to the docblock. 

So, PHP wouldn't complain if you return anything that can be converted to a string (a `UuidInterface` instance for example).

By the way, static analysis tools such as PHPStan will warn you about that.
The fast solution: add a rule in your `phpstan.neon` file to ignore such warning. 
I will probably remove such docblock in a near future but won't add a `UuidInterface` return typehint as you suggested to avoid BC.
