### ISSUE TITLE
Delete operations save the proxy discriminator

### ISSUE THREAD

**Issue by Nemo64** [DamienHarper/DoctrineAuditBundle#177]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.3.2
| PHP version                 |  7.3.14
| Database                    | MySQL 5.6.47 (ORM version 2.7.0)

#### Summary

Delete operations can save the proxy discriminator.

#### Current behavior

When I delete an entity that I didn't fully load before (using getReference) and delete it,
the audit bundle will save the proxy discriminator.
![Bildschirmfoto 2020-03-19 um 11 29 09](https://user-images.githubusercontent.com/1749936/77057841-de31a480-69d4-11ea-950e-bb03f55e4368.png)

I condsider this unexpected. The audit interface can't see those changes either.

#### How to reproduce

```php
// use any entity you like. My Entity here uses SingleTableInheritance (I didn't test if that makes a difference)
$employee = $this->entityManager->getReference(Employee::class, 1);
$this->entityManager->remove($employee);
$this->entityManager->flush();
```

#### Expected behavior

I expect the discriminator to always be the Entity class, not the Proxy class.

**Comment by DamienHarper** [comment]
@Nemo64 Can you please test again using `master` branch please?

**Comment by DamienHarper** [comment]
@Nemo64 Feel free to reopen this issue if needed.

**Comment by Nemo64** [comment]
I can confirm, it works beautifully. 👍 
Thanks a lot.
