### ISSUE TITLE
[question] can we use this bundle as a versionning tool ? 

### ISSUE THREAD

**Issue by kl3sk** [DamienHarper/DoctrineAuditBundle#18]
Because here it is not planned https://github.com/DATA-DOG/DataDogAuditBundle/issues/43 do you ?

Especially revert behaviour.

**Comment by DamienHarper** [comment]
Hi, I'm sorry but this is not on the roadmap right now.

**Comment by DamienHarper** [comment]
Though, I'd be happy to merge your PR if you want to contribute ;)

**Comment by kl3sk** [comment]
I’ve not yet test your bundle. I’ll disable datadog’s before. 

Then test your to see if it fit my needs (should, because of the idea of datadog). But not implemented reverting behaviour 😋

**Comment by DamienHarper** [comment]
I close this one for now

**Comment by kl3sk** [comment]
Yes I'll maybe reopen or do something else it if I found a way.

**Comment by kl3sk** [comment]
This is just a proposal, but a revert feature may be a great improvement:

https://github.com/DamienHarper/DoctrineAuditBundle/pull/98
