### ISSUE TITLE
Impersonation suport

### ISSUE THREAD

**Issue by alfabetagama** [DamienHarper/DoctrineAuditBundle#183]
HI,

If the user is impersonated, bundle should log both impersonated user and impersonator.
```
        if ($token instanceof SwitchUserToken) {
            $impersonator= $token->getOriginalToken()->getUser();
            $user = $token->getUser();
        }
```

**Comment by DamienHarper** [comment]
Hi @alfabetagama! Impersonator tracking has been implemented in `1.5.0`. Which version are you using?

**Comment by alfabetagama** [comment]
Hi, 

And thanks for quick response. You are correct, it is implemented and it is working. 

Best regards

**Comment by DamienHarper** [comment]
@alfabetagama no problem so I close the issue ;)
