### ISSUE TITLE
The `RoutingAnnotationLoader` breaks existing Annotation routes within the app

### ISSUE THREAD

**Issue by roygoldman** [DamienHarper/DoctrineAuditBundle#187]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | master
| PHP version                 | 7.3.14
| Database                    | MySQL / Maria

#### Summary

In an app that uses annotation loaders for most controllers, bringing in this project results in all other routes becoming unusable. 

#### Current behavior

 The new router implementation, added in 92201a2f, renders all other routes unusable, since the new implementation will return either an empty set or just the routes defined in `ViewerController`, when `enabled_viewer` is set.

#### How to reproduce

Add the bundle to an existing project with annotation based routes.

#### Expected behavior

Other routes to work.

#### Proposed solution

Don't implement a custom router. A simpler solution is to provide a default recipe, which includes a routing configuration which sets up the route with sane defaults, and allows the user more flexibility over location. The following configuration could be provided as [part of the existing recipe](https://github.com/symfony/recipes-contrib/blob/master/damienharper/doctrine-audit-bundle/).

```yaml
# /config/routes/dh_doctrine_audit.yaml
dh_doctrine_audit:
    resource: '@DHDoctrineAuditBundle\Resources\config\routes.yaml'
```
This configuration provides everything needed to setup the routes within an existing project, and lets us still track the routers internally. Alternatively, the existing config could be off loaded to the recipe, to provide more flexibility.

I started putting a patch together with this implementation, but wanted to get feedback about the ideal direction to take the project. Please let me know if you need additional information for testing/reproducing. I'll think this over and provide a pr soon if I don't hear anything back.

**Comment by DamienHarper** [comment]
@roygoldman I confirm the bug. Though we still need the custom routing annotation loader for the  `enabled_viewer` option. I'll push a patch soon.

**Comment by roygoldman** [comment]
Yes, while working on my implementation of a pr, I couldn't find another way to make the `enabled_viewer` config property work without the loader. However with the proposed solution, off loading the loading of the controller into the base application, eliminates the need for the property, since the app developer could simply remove the router there all together. By using the above embed, it lets the user not worry about the controller implementation, just that they need to import the routes as supplied by the project.

However, if there comes a need for multiple dynamically available controllers, it may cause some headaches.

**Comment by DamienHarper** [comment]
@roygoldman I pushed a patch to master but I like your idea to remove the custom loader and offload the controller loading to the base application. That way we could remove the compiler pass and the custom loader and make things easier/lighter.
Could you please submit your PR?

**Comment by DamienHarper** [comment]
@roygoldman finally, we'll keep the `enabled_viewer` flag and custom routing loader. Otherwise, even if I like the idea to simply things as you suggested, we'll loose the ability to dynamically enable/disable the viewer.

**Comment by DamienHarper** [comment]
I close this issue as it's fixed in `master`
