### ISSUE TITLE
Cannot load resource "@DHDoctrineAuditBundle/Controller/"

### ISSUE THREAD

**Issue by markus-fischbacher** [DamienHarper/DoctrineAuditBundle#194]
Hi there, 
I've installed the bundle as mentioned in the documents.
After adding the routes for Audit Viewer I get the following error:
```
 Cannot load resource "@DHDoctrineAuditBundle/Controller/". Make sure the "DHDoctrineAuditBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is register  
  ed, make sure the bundle path "@DHDoctrineAuditBundle/Controller/" is not empty.  
```

bundles.php

`    DH\DoctrineAuditBundle\DHDoctrineAuditBundle::class => ['all' => true],`

config/routes/dh_doctrine_audit.yaml
```
dh_doctrine_audit:
  resource: "@DHDoctrineAuditBundle/Controller/"
  type: audit
```

composer.json
 `   "damienharper/doctrine-audit-bundle": "^3.4",`

![image](https://user-images.githubusercontent.com/10846308/80029878-b78cef00-84e7-11ea-96cc-66c43d4019c3.png)

I've no idea, why it's not working.

Any help is appreciated.
Markus

**Comment by markus-fischbacher** [comment]
Just found it by myself.
The official documentation shows the following configuration:
```
dh_doctrine_audit:
    resource: "@DHDoctrineAuditBundle/Controller/"
    type: audit
```

If you're using the following, it's working
```
dh_doctrine_audit:
  resource: "@DHDoctrineAuditBundle/Controller/"
  type: annotation
```

**Comment by DamienHarper** [comment]
@markus-fischbacher Glad you found a fix yourself ;) 
I suppose you read the doc from `master` branch which is currently under heavy development for next major version `4.0`. 
The doc of the latest "stable" version `3.4.0` is located in `3.x` branch. [Click here](https://github.com/DamienHarper/DoctrineAuditBundle/blob/3.x/doc/30-audit-viewer.md) to view the section related to the viewer.

**Comment by markus-fischbacher** [comment]
@DamienHarper yes, you‘re right. I read the master branch documentation. Thanks for the clarification. BTW it’s a cool bundle. I‘m curious about the new version.
