### ISSUE TITLE
ManyToMany missing dissociate event

### ISSUE THREAD

**Issue by scion4581** [DamienHarper/DoctrineAuditBundle#21]
Hello! I face some trouble, having many to many relation when you remove last association there is no dissociative event record in audit table for that entity
Everything else seems working fine

**Comment by DamienHarper** [comment]
@scion4581 could you provide me some sample code to reproduce your issue?

**Comment by kl3sk** [comment]
Look at the FAQ entry in the read me. 

I had a similar problème.

**Comment by scion4581** [comment]
which one example? there is no need some code to show

1)just create many to many relation ,for example, books vs tags, 
2)add two tags to a book - u will see associate event
3)then remove one - u will see dissociate event
4)but when u will remove last one - another dissociate event is missing

Or you have another behavior?

P.S. I admit that this is happens when u remove all many to many accosiations with another entity, no matter if it was one, two or many more. In example above this is happens when u remove all tags

**Comment by scion4581** [comment]
@kl3sk to add just another entity to audit proccess working fine

**Comment by scion4581** [comment]
Little investigation point that in [this line](https://github.com/DamienHarper/DoctrineAuditBundle/blob/4b2be4642f6c5581cca2451220fc11737cb1d5c8/src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php#L138) $collection->toArray() empty after delete all associations...

BTW I am using form for entity editing maybe problem is there, I will try use only code and will post result later

**Comment by scion4581** [comment]
Seems I found the problem its related to https://github.com/doctrine/mongodb-odm/issues/1559
While its mongodb repo problem actual in my case too
So if you will use collection->clear() you won't be able to catch associations has been removed,
just get empty collection
In my case I was not call clear by myself instead this action provided by one form listener bellow [link](https://github.com/symfony/symfony/blob/737726516e819fc0b1ea43dc6491bddd6d98b1f4/src/Symfony/Bridge/Doctrine/Form/EventListener/MergeDoctrineCollectionListener.php#L49)

So I am thinking about possible solutions... 
Remove somehow that listener, its hard cause it in form eventdispacther or save old collection before submit and in 'onFlush' event check if collection is empty then force changes recording...

Sorry about my eng, far from perfect:(

**Comment by DamienHarper** [comment]
@scion4581 I'm sorry but I don't think I can help much on that issue :/
Maybe you can try to register a custom `MergeDoctrineCollectionListener` event listener with higher priority so that it's run before the default one and override its behavior regarding the collection clearing but it looks quite challenging.

**Comment by scion4581** [comment]
@DamienHarper, Unfortunately MergeDoctrineCollectionListener not defined like service, it just passes like ->addEventSubscriber(new MergeDoctrineCollectionListener()), so there is nothing you can do :(
