### ISSUE TITLE
@Tempalte annotation

### ISSUE THREAD

**Issue by kl3sk** [DamienHarper/DoctrineAuditBundle#22]
Because i use api-platform as backend (correct me if i'm wrong) it doesn't require `sensio/framework-extra-bundle` which is needed to load `@Tempalte` annotation which is in your `AudiController`

I think of 2 solutions:

1- Add requirement in you `composer.json`
2- Remove the annotations in you controller (in fact you use `$this->render`)

For me the second solution seems better

**Comment by DamienHarper** [comment]
Thanks @kl3sk, well spotted. It's fixed right now in `master` branch.

**Comment by kl3sk** [comment]
`composer update` or `composer remove && composer req` doesn't do anything

**Comment by DamienHarper** [comment]
@kl3sk I only removed an unused dependency to SensioFrameworkExtraBundle in a controller so composer won't do anything by itself. 
If the extra bundle has been added to your project, you have to remove it yourself: `composer remove sensio/framework-extra-bundle`

**Comment by kl3sk** [comment]
@DamienHarper  Yes I know that, what I mean that `your` bundle isn't update even on update or remove and install 😃

**Comment by DamienHarper** [comment]
@kl3sk my commit has been done on `master` branch and I haven't tagged it for release so composer can't update anything. 
If you want to try the `master` branch, you have to edit your `composer.json` file and change the version requirement regarding DoctrineAuditBundle to `dev-master` 
ie `"damienharper/doctrine-audit-bundle": "dev-master"`

**Comment by kl3sk** [comment]
Ok thank you 👍
