### ISSUE TITLE
ApiPlatform compatibility

### ISSUE THREAD

**Issue by kl3sk** [DamienHarper/DoctrineAuditBundle#23]
Because audited entities are not "real" entity i can't tell (as I know) ApiPlatform to expose it.

I try to find a way but any help will be appreciated.

I found a way to expose vendor entities here https://github.com/api-platform/api-platform/issues/891 but with you bundle I don't know yet.

**Comment by DamienHarper** [comment]
@kl3sk is this issue still relevant?
