### ISSUE TITLE
Add support for custom user provider

### ISSUE THREAD

**Issue by eduardoweiland** [DamienHarper/DoctrineAuditBundle#26]
Currently, this bundle only supports getting the user from Symfony's `TokenStorage`. Is it possible to add something like [getting the user from a custom service](https://github.com/simplethings/EntityAuditBundle#setting-the-current-username)? We are using Symfony in a microservices architecture and we don't use `TokenStorage` to save the current user. With this bundle we have no way to implement a custom logic for getting the user.

I think that replacing the direct usage of `TokenStorage` with something like an `AuditUserProviderInterface` will provide the required flexibility, and this bundle could provide a default implementation that still uses `TokenStorage`. I'm afraid that for this to work we have to [change the `AuditConfiguration` constructor](https://github.com/DamienHarper/DoctrineAuditBundle/blob/cdac88c24b78e1aceaa0c4bfd47da8d72bb4ee47/src/DoctrineAuditBundle/AuditConfiguration.php#L40) and possibly break compatibility. But, if it is ok I can work on a PR.

**Comment by DamienHarper** [comment]
Hi @eduardoweiland, thanks for your feedback. I was thinking about using `TokenStorageInterface` in place of `TokenStorage` class to make things a bit more flexible. 
Does your "user provider" implement `TokenStorageInterface`?

**Comment by eduardoweiland** [comment]
I was thinking in something that does not require `symfony/security` to be installed to work. You can see what I made so far [in my fork](https://github.com/DamienHarper/DoctrineAuditBundle/compare/master...quantosobra:user-provider).

**Comment by DamienHarper** [comment]
Looks great, feel free to make a PR as soon as your done ;)

**Comment by eduardoweiland** [comment]
@DamienHarper PR created #27
