### ISSUE TITLE
README.md for Symfony 4

### ISSUE THREAD

**Issue by PinDeZebra** [DamienHarper/DoctrineAuditBundle#29]
Hi, thanks for the bundle. I just intalled it with Symfony 4 and would have some minor improvements recommendation for the README.md related to Symfony 4 specifically:

- The "Step 2: Enable the Bundle", is not needed anymore : the bundle is added automatically to config\bundles.php which in turn is read by the Kernel.php.
- In "Configuration", the dh_doctrine_audit config file location that worked for me was : config/packages/dh_doctrine_audit.yaml 
- In "Configuration Audit viewer", I would recommend the file "config/routes/annotations.yaml" as a better choice than "config/routes.yaml"

Great work!

**Comment by DamienHarper** [comment]
@PinDeZebra thanks for your feedback

**Comment by DamienHarper** [comment]
@PinDeZebra 

> The "Step 2: Enable the Bundle", is not needed anymore : the bundle is added automatically to config\bundles.php which in turn is read by the Kernel.php.

Step 1 and Step 2 are required for "Applications that don't use Symfony Flex". As you are using Symfony 4.2 hence Symfony Flex, you only need the `composer require damienharper/doctrine-audit-bundle` (cf. "Applications that use Symfony Flex" from `README.md`)

> In "Configuration", the dh_doctrine_audit config file location that worked for me was : config/packages/dh_doctrine_audit.yaml

You're right I mistyped the path => I'll fix the `README.md`

> In "Configuration Audit viewer", I would recommend the file "config/routes/annotations.yaml" as a better choice than "config/routes.yaml"

Symfony doc mentions the `routes.yaml` file for "simple applications" (cf. https://symfony.com/doc/current/routing/external_resources.html)
But you can also use the `annotations.yaml`file if you prefer/are more used to.

**Comment by DamienHarper** [comment]
@PinDeZebra config file path is [fixed](https://github.com/DamienHarper/DoctrineAuditBundle/commit/9161f165f16a01d207278bc5876cff56932d8aca) in `README.md`
