### ISSUE TITLE
PostgreSQL schemas not supporting

### ISSUE THREAD

**Issue by DrummerKH** [DamienHarper/DoctrineAuditBundle#32]
We are using PostgreSQL database. We have tables in schema 'scheme' which must be audited. With default bundle configuration audit tables creating in correct table's schema, but on insert changes to audit tables the schema is ignored and doctrine trying save to default 'public' scheme.

**Comment by DrummerKH** [comment]
I suggesting this patch https://github.com/DamienHarper/DoctrineAuditBundle/pull/33

**Comment by DamienHarper** [comment]
@DrummerKH good catch! Thanks for your feedback, I'll have a close look at your PR.

**Comment by DrummerKH** [comment]
I found where need to add schema support also - in AuditViewer, now i`m updating PR.

**Comment by DrummerKH** [comment]
It is done, check it please.

**Comment by DamienHarper** [comment]
PR #33 looks OK to me and has been merged into `master`. However, I do not have any PostgreSQL at hand right now so I can't test it properly. 
@DrummerKH can you confirm it's ok on your side?

**Comment by DamienHarper** [comment]
I close this one as 1.4.0 is out
