### ISSUE TITLE
Issues with class inheritence

### ISSUE THREAD

**Issue by kezek** [DamienHarper/DoctrineAuditBundle#34]
Hi there. First of all thanks for the bundle.

Having an issue with a specific use case:

1. Having a class X (normal doctrine entity , not mapped superclass) which is marked as auditable 
2. Having a class Y (another normal doctrine entity) which extends X (Y extends X), not marked as auditable 

Getting an Undefined index: Y , in src/DoctrineAuditBundle/AuditConfiguration.php:95 . Checked the code there and I think it's because isAudited return true due to Y instanceof X being true.

Don't have time to push a PR currently :(

**Comment by DamienHarper** [comment]
I pushed a fix in `master` branch. 
Can you please confirm it fixes your issue.

**Comment by kezek** [comment]
I will let you know as soon as possible !

**Comment by DamienHarper** [comment]
1.4.0 is out and should fix this issue. Feel free to re-open if it's not the case.
