### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by snuffer82** [DamienHarper/DoctrineAuditBundle#35]
hi, 
I try to install through composer but I received this message error:
`Could not find package damienharper/doctrine-audit-bundle at any version matching your PHP version 7.0.32.0`
What can I do?
thanks a lot
Paolo

**Comment by DamienHarper** [comment]
Hi @snuffer82, the bundle requires a PHP version >= 7.1. The best advice I can give you is: update PHP to 7.1 at least, 7.0 is not supported anymore.
