### ISSUE TITLE
Why an extra table for each entity?

### ISSUE THREAD

**Issue by olek07** [DamienHarper/DoctrineAuditBundle#39]
Hi!
Why do you create an extra table for each entity? You could store all of the audits into the only one table "audit", that contains an additional field "entity" with the name of the correspondent entity. Can you add this option to the config?

**Comment by DamienHarper** [comment]
@olek07 This is by design for performance reason: a single table to collect all audits from every other tables makes it a bottleneck in a system where there are many concurrent writes on audited tables. 
Database locking and table size become quickly a big concern in such situations.
