### ISSUE TITLE
Table associations questions

### ISSUE THREAD

**Issue by marcoreni** [DamienHarper/DoctrineAuditBundle#4]
Hello again,

I'm experimenting with the bundle, and I have a few questions about associations tracking.

## OneToOne bi-directional associations

I have some associations mapped as:
```php 
// EntityOne.php
class EntityOne
{
    /* [...] */

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\CorrelatedEntity",
     *     inversedBy="entityOne",
     *     fetch="LAZY",
     *     cascade={"persist"})
     */
    private $correlatedEntity;
     
    /* [...] */
}


// CorrelatedEntity.php
/*
 * @Entity
 */
class CorrelatedEntity
{
    /* [...] */

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\EntityOne", mappedBy="correlatedEntity")
     * @ORM\JoinColumn(name="entity_one_id", referencedColumnName="id")
     */
    private $entityOne;

    /* [...] */
}
```

After adding a `CorrelatedEntity` to an existing `EntityOne`, I can see a change tracked inside `EntityOne`:

| Properties | Old value | New value |
| --- | --- | --- |
| correlatedEntity | | label: AppBundle\Entity\CorrelatedEntity#3<br> class: AppBundle\Entity\CorrelatedEntity <br> table: correlated_entity<br> id: 3 |

And an insertion inside `CorrelatedEntity`:

Properties | Old value | New value
--- | --- | ---
id | | 3
data | | test_test
| entityOne | | label: AppBundle\Entity\EntityOne#1<br> class: AppBundle\Entity\EntityOne<br> table: entity_one<br> id: 1

Inside the bundle code I saw that there is a "associated" / "disassociated" change type, so I'm wondering: 
1. Is there a way to navigate between the associations inside the template?

## OneToMany bi-directional associations

I have some associations mapped as:
```php 
// EntityOne.php
/**
 * @ORM\Entity
 */
class EntityOne
{
    /* [...] */
    
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\EntityTwo",
     *     mappedBy="entityOne", cascade={"persist"})
     */
    private $entityTwos;
     
    /* [...] */
}


// EntityTwo.php
/**
 * @ORM\Entity
 */
class EntityTwo
{
   /* [...] */
   
   /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\EntityOne",
     *     inversedBy="entityTwos", cascade={"persist"})
     * @ORM\JoinColumn(name="entity_one_id", referencedColumnName="id")
     */
    private $entityOne;

    /* [...] */
}
```

After adding one or more `EntityTwo` to an existing `EntityOne`, I can see an insert tracked inside `EntityTwo`:

| Properties | Old value | New value |
| --- | --- | --- |
| id | | 6
| additional_data | | datatest
| entityOne | | label: Proxies\__CG__\AppBundle\Entity\EntityOne#8<br>class: AppBundle\Entity\EntityOne<br>table: entity_one <br> id: 8 |

But on `EntityOne` I don't see any change.

1. Why the association is not tracked both ways? Am I missing something inside the configuration or inside the association declaration?
2. Is there a way to navigate between the associations inside the template?

## ManyToMany unidirectional associations

I have some associations mapped as:
```php 
// EntityOne.php
/**
 * @ORM\Entity
 */
class EntityOne
{
    /* [...] */
    
    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\EntityThree", cascade={"persist"})
     * @ORM\JoinTable(schema="my_schema", name="entity_three")
     *
     */
    private $entityThrees;
     
    /* [...] */
}


// EntityThree.php
/**
 * @ORM\Entity
 */
class EntityThree
{
   /* [...] */
}
```

After adding one or more `EntityThree` to an existing `EntityOne`, I'm not able to see the association anywhere.

1. Do I have to explicitly map the relation inside the configuration somehow?

Thanks in advance,
Marco

**Comment by DamienHarper** [comment]
@marcoreni Thanks for your feedback.
As of now, there is no navigation in the template, I plan to add some as well as a more polished look in the future (low priority right now - no ETA)
I need some more time to investigate the other issues, I'll report asap.

**Comment by DamienHarper** [comment]
Hi @marcoreni 
`association` and `dissociation` were only used with `ManyToMany` relationships. 
I've just pushed some updates to dev-master that enables them for OneToMany as well. 

Also, I think that in your "ManyToMany unidirectional associations" `EntityThree` code sample, you miss the inverse part of the relationship with `EntityOne`. 

You should have something like:
```
// EntityThree.php
/**
 * @ORM\Entity
 */
class EntityThree
{
   /* [...] */

   /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EntityOne", mappedBy="entityThrees", cascade={"persist"})
     */
    protected $entityOnes;

   /* [...] */
}
```

Can you please test agains dev-master and report me back? I'll push a 1.0.5 release if everything's ok.

**Comment by marcoreni** [comment]
Hello @DamienHarper , I'll test & report back `dev-master` ASAP.

As for the ManyToMany case, it's a **unidirectional** association as documented here:  http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#many-to-many-unidirectional

That's why there is no inverse side. I know I won't be able to see the relation on the "unmapped" side, but does this mean that I won't be able to see it anywhere?

**Comment by DamienHarper** [comment]
@marcoreni no, there's no need to use bidirectional relationships.
You should see association from owning side only regarding unidirectional relationships and from both sides regarding bidirectional relationships.

**Comment by DamienHarper** [comment]
@marcoreni 1.0.5 released

**Comment by marcoreni** [comment]
Hello @DamienHarper , sorry for my terrible delay.

I'm testing 1.0.5 right now.

I was able to see Associations in One-To-Many bi-directional relationships.
I also tried disassociations. The change was tracked, but inside "Object ID" I can see the object id of the target entity (ie. I disassociated entityOne#13 and entityTwo#9. Inside entityOne history, I see `Type: disassociate - Object id: 9` instead of `Object id: 13`

About many-to-many one-directional, it was my mistake. I thought that, since the mapping was uni-directional and I had no intention of tracing the "other side", it wasn't necessary to add the nonmapped entity inside my configuration. I now added that entity too and I can see the association/disassociation, even though there is the same issue as before (Object id is the one from the target entity).

Thanks again for your help
Marco

**Comment by DamienHarper** [comment]
@marcoreni In your example you disassociated entityOne#13 and entityTwo#9. 
So inside entityOne history, you see `Type: disassociate - Object id: 9` which means from entityOne point of view, it's been dissociated from entityTwo#9.

**Comment by marcoreni** [comment]
@DamienHarper I got that, but this way in the change history for a particular entity#id I won't see the disassociation, because for that particular case the id will be the one from the target entity, while for all other cases it will be the one from the parent entity.

In the example below I've been working only with entityOne#10:

![image](https://user-images.githubusercontent.com/2797489/38765978-7b5cd486-3fcb-11e8-94f3-5f4682267155.png)

Therefore, if I click on the object Id 10 I will be able to see all history for that particular object, except the disassociation.

Is this expected behaviour?

**Comment by DamienHarper** [comment]
@marcoreni for short, right now every `association` and `dissociation` that comes from a collection operator (ie done using adder and/or remover) is listed as `associate` and `dissociate` operations in histories.
On the other hand, every `association` and `dissociation` that comes from a setter is listed as `update` operations in histories.


Excerpt of `EntityOne` class:
```php
...
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\EntityTwo",
     *     mappedBy="entityOne", cascade={"persist"})
     */
    private $entityTwos;
...
    /**
     * Add EntityTwo entity to collection (one to many).
     *
     * @param \App\Entity\EntityTwo $entityTwo
     *
     * @return EntityOne
     */
    public function addEntityTwo(\App\Entity\EntityTwo $entityTwo)
    {
        $this->entityTwos[] = $entityTwo;
        $entityTwo->setEntityOne($this);

        return $this;
    }

    /**
     * Remove EntityTwo entity from collection (one to many).
     *
     * @param \App\Entity\EntityTwo $entityTwo
     *
     * @return EntityOne
     */
    public function removeEntityTwo(\App\Entity\EntityTwo $entityTwo)
    {
        $this->entityTwos->removeElement($entityTwo);
        $entityTwo->setEntityOne(null);

        return $this;
    }
...
```

Calling `EntityOne::addEntityTwo()` will generate 
* an `associate` operation in `EntityOne` history
* an `update` operation in `EntityTwo` history

Calling `EntityOne::removeEntityTwo()` will generate 
* a `dissociate` operation in `EntityOne` history 
* an `update` operation in `EntityTwo` history



Excerpt of `EntityTwo` class:
```php
...
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\EntityOne",
     *     inversedBy="entityTwos", cascade={"persist"})
     * @ORM\JoinColumn(name="entity_one_id", referencedColumnName="id")
     */
    private $entityOne;
...
    /**
     * Set the value of entityOne.
     *
     * @param \App\Entity\EntityOne $entityOne
     * @return \App\Entity\EntityOne
     */
    public function setEntityOne(?\App\Entity\EntityOne $entityOne)
    {
        $this->entityOne = $entityOne;
        return $this;
    }
...
```

Calling `EntityTwo::setEntityOne()` will generate an `update` operation in `EntityTwo` history only.
