### ISSUE TITLE
Improvement: Config option for auditing on insert/update/others?

### ISSUE THREAD

**Issue by sigma-technology** [DamienHarper/DoctrineAuditBundle#43]
What do you think about having a configuration option for whether the bundle should record changes on insert and update, or only update?  I'm guessing this could also technically be applied to any ORM operation.

Currently, it is logging the 'changes' on initial flush when an entity is created; the previous value is null and the new value is whatever the property is set to when created.  We have 'created' and 'updated' properties on the entity itself so this initial audit trail is not really necessary.

**Comment by DamienHarper** [comment]
@sigma-technology I agree that one could consider these initial details useless and only take into account the `insert` operation type. Though, an audit trail has to log details about every change applied to an entity (including creation details). This makes it easier to review an entity lifecycle without having to "reverse replay" every change to get its initial state.

**Comment by sigma-technology** [comment]
Sorry, I read this then forgot to reply. I agree with you anyway - I got lost in my particular use-case.
