### ISSUE TITLE
Proxy classes are considered as not audited since 1.4.0

### ISSUE THREAD

**Issue by blesenechal** [DamienHarper/DoctrineAuditBundle#44]
Since 1.4.0 and this commit (https://github.com/DamienHarper/DoctrineAuditBundle/commit/c839ee80d3c65b1af81f5d4e7dae4149e95ebe42), the "is_subclass_of" test added makes "isAudited" return false if the argument is a proxy (because the proxy is a subclass of the enity)

> if (\is_object($entity) && $entity instanceof $auditedEntity && !is_subclass_of($entity, $auditedEntity)) {

But when working with Doctrine, we often get a proxy instead of the entity.

In my case, we have users linked to orders.
When calling the getUser() method of the order, we get a proxy on the User (class is Proxies\__CG__\App\Entity\User).
But then making changes on the user, the proxy class is considered as not audited

The same code works fine with 1.3.0.

**Comment by DamienHarper** [comment]
@blesenechal could you please try `master` branch, it should fix your issue. Please, let me know.

**Comment by blesenechal** [comment]
@DamienHarper That fixes the issue for me :)
