### ISSUE TITLE
Change is not tracked for boolean from: null to: false (or vice-versa)

### ISSUE THREAD

**Issue by marcoreni** [DamienHarper/DoctrineAuditBundle#5]
Hello again,

I have some boolean nullable fields inside my entities. If I change one of these fields from false to null, the change is not tracked. If I change it from true to false, or from true to null, the change is tracked in both cases but I cannot see the difference inside the diff (in both cases I see `from: 1 - to: {empty}`.

The audit table shows:
```json
// (true => null)
{
    "theField": {
        "new": null,
        "old": true
    }
}

// (true => false)
{
    "theField": {
        "new": false,
        "old": true
    }
}
```

I think this is because `false == NULL` ( http://php.net/manual/en/types.comparisons.php#types.comparisions-loose ).

I would submit a PR but I'm not entirely sure about the implications of changing the loose ifs inside https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php#L276 && https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/src/DoctrineAuditBundle/EventSubscriber/AuditSubscriber.php#L284 for other types

**Comment by DamienHarper** [comment]
@marcoreni thanks for your feedback again. I think you're right, this issue could come from these non strict comparisons. Feel free to make a PR and test on your side. I'll do the same and merge it if all good.
