### ISSUE TITLE
Custom User informations

### ISSUE THREAD

**Issue by NOaMTL** [DamienHarper/DoctrineAuditBundle#56]
Hello,

I would like to know the best way to store in the audit table more informations about the user, like the first name, last name and avatar (I use default userprovider). What is the best way ?

Thank you.

**Comment by DamienHarper** [comment]
@NOaMTL Could you please explain why you'd need such additional data.

As a reminder:
- version 1.x of the bundle stores `blame_user_id` and `blame_user` for each audit entry.
- version 2.x, in addition to `blame_user_id` and `blame_user`, the bundle  stores `blame_user_fqdn` and `blame_user_firewall`

Here is what these information mean:
- `blame_user_id` is the ID of the user who originated the audit entry 
- `blame_user` is the username of the user who originated the audit entry  
- `blame_user_fqdn` is the fully qualified class name of the user object who originated the audit entry 
- `blame_user_firewall` is the firewall name that was used

With all these information, at least `blame_user_id` and `blame_user_fqdn`, you should be able to retrieve the user object (so all its properties) who originated the audit entry

**Comment by DamienHarper** [comment]
@NOaMTL I close this issue as it hasn't received any feedback. Feel free to re-open it if necessary.
