### ISSUE TITLE
Single id is not allowed on composite primary key in entity

### ISSUE THREAD

**Issue by webmasterMeyers** [DamienHarper/DoctrineAuditBundle#57]
My solution to this will be just to add an ID as per normal, but it is actually unnecessary from a data integrity point of view.

The entity is part of a ManyToMay table. [App\Entity\FamilyBrBeneficiaryProfilePerson]  It is a "family" record that links a "beneficiary profile" to a "person" and contains a couple of extra data points.
````
    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\BeneficiaryProfile", inversedBy="family")
     * @ORM\JoinColumn(nullable=false)
     */
    private $beneficiaryProfile;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\Person", inversedBy="dependantProfiles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $person;
````
in PostgreSql this is simply a `PRIMARY KEY (beneficiary_profile_id, person_id)`

As I said, my work around will be to add the usual single `id` key and then add a unique constraint on the other id's.

Not sure if this is worth trying to support or not, but I thought I'd share.

**Comment by DamienHarper** [comment]
@webmasterMeyers Right now I don't plan to add support to composite primary keys any time soon unless demand gets higher. Though, I'm open to any PR that add such support.

**Comment by mrtnzagustin** [comment]
Any possible update on this? i'll look to consider making a PR

**Comment by DamienHarper** [comment]
@mrtnzagustin i still don’t plan to add support of composite primary keys. 
It would require quite important changes to the current code base such as changing the way we currently store object ids in every audit table. 
This would also imply some backward compatibility headaches regarding users currently using the bundle in prod, ie. users having actual (single column primary key based) audit data.

**Comment by timwsuqld** [comment]
Just adding weight here, this is something we need. I'm working with a structure we can't change, and would still love to be able to use the audit. Given the table structure for `id` isn't a FK, it shouldn't be too hard to store the key in a similar way that MySQL/Doctrine already throw errors about, something like `12-5555`. Or is part of the concern that parts of the ID could change over the lifetime of that row, so your ID isn't static?
