### ISSUE TITLE
README.md AuditViewer

### ISSUE THREAD

**Issue by pedrocasado** [DamienHarper/DoctrineAuditBundle#64]
The AuditViewer depends on Pagerfanta bundle which is not loaded by default in Symfony 3. So in AppKernel.php i have to enable the bundle, otherwise we  have the error:

`Unknown "pagerfanta" function.`

In AppKernel.php:

    public function registerBundles()
    {
        $bundles = array(
            // ...
            new DH\DoctrineAuditBundle\DHDoctrineAuditBundle(),
            new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),
        );
    }

**Comment by DamienHarper** [comment]
@pedrocasado Thanks for the report, I'll update the `README.md`

**Comment by DamienHarper** [comment]
@pedrocasado it will be fixed in next release
