### ISSUE TITLE
User with uuid as id

### ISSUE THREAD

**Issue by hason** [DamienHarper/DoctrineAuditBundle#66]
I use UUID as identifier for User entity. Your code assumes that `id` is integer https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/src/DoctrineAuditBundle/User/UserInterface.php#L7

Application throws error
```
Notice: A non well formed numeric value encountered
```

**Comment by DamienHarper** [comment]
@hason sorry for this late reply, I've been very busy lately. I'll have a closer look at your issue asap

**Comment by DamienHarper** [comment]
@hason can you test against `master` branch?

**Comment by DamienHarper** [comment]
I close this issue for now. Feel free to reopen if needed.
