### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Jelvooo** [DamienHarper/DoctrineAuditBundle#67]
I install the package with
`composer require damienharper/doctrine-audit-bundle`

After that I setup my dh_doctrine_audit.yaml
```
dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration

    entities:
        App\Entity\ServiceTemplate: ~
#        MyBundle\Entity\MyAuditedEntity1: ~   # all MyAuditedEntity1 properties are audited
#        MyBundle\Entity\MyAuditedEntity2:
#            ignored_columns:                  # MyAuditedEntity2 properties to be ignored by the audit process
#                - createdAt
#                - updatedAt

```

`php bin/console doctrine:schema:update --dump-sql `

When I update my database after that it says there aren't any changes. The package doesn't add views or entity's or something to my project. How can I install it on the right way?

**Comment by DamienHarper** [comment]
@Jelvooo Hi, did you clear your cache before running the `bin/console doctrine:schema:update --dump-sql` command?

**Comment by Jelvooo** [comment]
Hi @DamienHarper , I tried to clear it now but it still says no changes

**Comment by DamienHarper** [comment]
Hum that's strange...
Are you on Symfony 4 or Symfony 3.4? 
Is doctrine metadata cache enabled? If yes, what king of cache is configured (filesystem, APCu, Redis...)?

**Comment by DamienHarper** [comment]
@Jelvooo any news about this?

**Comment by Jelvooo** [comment]
Hey @DamienHarper tuesday I am at work again. Then i will look into it, the cache is filesystem.

**Comment by DamienHarper** [comment]
@Jelvooo okay, try emptying the cache folder (`rm -rf /path/to/project/var/cache/*` on linux for example)

**Comment by Jelvooo** [comment]
Still " [OK] Nothing to update - your database is already in sync with the current entity metadata."

**Comment by Jelvooo** [comment]
I only have 1 file added by the way, the dh_doctrine_audit

**Comment by DamienHarper** [comment]
@Jelvooo that’s very strange. Can you try to run `bin/console doctrine:migrations:diff` and look at the generated migration please?
If your project is quite small (and shareable), could you please send me a zip of the project so that I can have a closer look?

**Comment by Jelvooo** [comment]
Sorry I can't share the project. If I run the command it wants to open a file editor with this content:
```
#!/usr/bin/env php
<?php

use App\Kernel;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

set_time_limit(0);

require dirname(__DIR__).'/vendor/autoload.php';

if (!class_exists(Application::class)) {
    throw new RuntimeException('You need to add "symfony/framework-bundle" as a Composer dependency.');
}

$input = new ArgvInput();
if (null !== $env = $input->getParameterOption(['--env', '-e'], null, true)) {
    putenv('APP_ENV='.$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = $env);
}

if ($input->hasParameterOption('--no-debug', true)) {
    putenv('APP_DEBUG='.$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = '0');
}

require dirname(__DIR__).'/config/bootstrap.php';

if ($_SERVER['APP_DEBUG']) {
    umask(0000);

    if (class_exists(Debug::class)) {
        Debug::enable();
    }
}

$kernel = new Kernel($_SERVER['APP_ENV'], (bool) $_SERVER['APP_DEBUG']);
$application = new Application($kernel);
$application->run($input);

```

**Comment by DamienHarper** [comment]
Did you prepend the command with php? (`php bin/console...`)?
I suspect something’s wrong in your project, it should have created a migration :/

**Comment by Jelvooo** [comment]
No migration created :(

I used php bin/console yes.

**Comment by DamienHarper** [comment]
Hi @Jelvooo, do you still face this issue? I haven't been able to reproduce it on my side

**Comment by DamienHarper** [comment]
Closed as I haven't been able to reproduce the issue and no feedback have been provided for a month.
