### ISSUE TITLE
Revision reference to see all changes made in one transaction

### ISSUE THREAD

**Issue by n3o77** [DamienHarper/DoctrineAuditBundle#69]
Thank you very much for this bundle @DamienHarper .

Is it possible to have a revision number which bundles all changes made in one transaction? i.E. when updating a entity with many relations it would be nice to get all these changes without relying on user and timestamp.

**Comment by DamienHarper** [comment]
Hi @n3o77!
Revision number is not on the roadmap right now as you are the first one to request such a feature.
I need to think about it a bit more.

**Comment by n3o77** [comment]
Thanks for considering it. I might need this soon in a project so i'm happy to send you a PR but would love to get your input on it first.

**Comment by DamienHarper** [comment]
@n3o77 Great, I'd be happy to review it

**Comment by DamienHarper** [comment]
@n3o77 I just merged a feature that should fulfill your request, can you test `master` branch and provide some feedback?

**Comment by n3o77** [comment]
@DamienHarper you're awesome, thank you so much! I'll check it out in a bit.

**Comment by n3o77** [comment]
Looks good so far. Only thing missing is the view. 

Again, thank you very much!

**Comment by DamienHarper** [comment]
Yeah, I'm working on it ;) 
But I wanted to push the main (backend) part early to get feedback before really working on the UI part.

**Comment by DamienHarper** [comment]
@n3o77 timeline now displays the transaction hash for each element. By clicking a transaction hash, you get a complete overview of the operations included into the transaction.
Just checkout `master` branch and give me some feedback please ;)

**Comment by n3o77** [comment]
Looks awesome. One little bug: if you update to this version with existing data and there's no hash it throws an error because the route can't be generated here: https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/src/DoctrineAuditBundle/Resources/views/Audit/entry.html.twig#L18

**Comment by DamienHarper** [comment]
Good catch, a fix is on its way

**Comment by DamienHarper** [comment]
@n3o77 should be fixed on `master` branch

**Comment by n3o77** [comment]
looks good!

**Comment by DamienHarper** [comment]
Ok, it will be part of next major release. 
I close this issue. Feel free to reopen it if needed.
