### ISSUE TITLE
Enable auditing for all entities

### ISSUE THREAD

**Issue by Herz3h** [DamienHarper/DoctrineAuditBundle#87]
Hello,

How do you enable auditing for all entities ?

Another question: Is it possible to use the views for [DATA-DOG/DataDogAuditBundle](https://github.com/DATA-DOG/DataDogAuditBundle) ?

**Note:** Also I see that in the README it is said that this bundle is inspired by [DATA-DOG/DataDogAuditBundle](https://github.com/DATA-DOG/DataDogAuditBundle), it would be nice to mention the key differences.

Thanks

**Comment by DamienHarper** [comment]
@Herz3h Hi, thanks for your feedback. 
You have to list all of your entities in the configuration file to enable auditing for all of them.
Regarding your note about key differences between this bundle and DATA-DOG/DataDogAuditBundle, you're right: there is nothing about this in the `README.md`

Let me try to list a few key differences:
- DoctrineAuditBundle stores audits in separate audit tables which is way better when a lot of writes are done on audits and also split the weight of audits across different tables
- DoctrineAuditBundle lets you store audits in a separate database (breaks atomicity but may be useful depending on the use-case)
- DoctrineAuditBundle lets you enable/disable auditing at runtime, per entity and globally
- DoctrineAuditBundle is unit tested (94% code coverage)
- DoctrineAuditBundle offers a more detailed overview of audits (with a timeline view)
- DoctrineAuditBundle keeps track of which user, IP address and User-Agent were used
- DoctrineAuditBundle is compatible out of the box with SoftDeletable Doctrine extension ([StofDoctrineExtensionsBundle (Symfony Bundles Docs)](https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html))
- DoctrineAuditBundle lets you configure which timezone to use when storing creation date/time
- DoctrineAuditBundle provides an easy way to cleanup audit tables

**Comment by DamienHarper** [comment]
@Herz3h I close this issue as it hasn't received feedback recently. 
Feel free to re-open it if needed.

**Comment by Tersoal** [comment]
Hi.

This bundle sounds interesting. I work with knp doctrine behaviors, blameable and softdeletable options. Are they supported like stof?

Thank you for your great job.

**Comment by DamienHarper** [comment]
@Tersoal Thanks for your interest. This bundle is compatible with stof extensions, it is designed to work with softdeletable and as far as I know it is ok with other extensions.

**Comment by Tersoal** [comment]
Thank you so much. I will try this bundle for audit my entities. I see that logs are saved as raw SQL... I enjoy it!

Again, good job and thank you for your time and effort.

**Comment by Herz3h** [comment]
Ok thank you for the detailed differences between the two bundle. Unfortunately we have around 150 tables and that will probably increase as time goes. So enabling every entity manually is not convenient so we'll have to opt for another audit tool. Thank you for your efforts tough !

**Comment by DamienHarper** [comment]
@Herz3h Now that v3.0 is out, you can also easily mark an entity as auditable thanks to an annotation. 
Personally I use the bundle at work on several projects, one of them is housing around 400 tables, 3/4 of them are audited, new ones are created regularly and this is not a problem, our developers follow internal development guidelines covering the use of the `@Auditable` annotation.

**Comment by hardiksinh** [comment]
@DamienHarper As you mentioned above 

> "DoctrineAuditBundle is compatible out of the box with SoftDeletable Doctrine extension"

this should work with soft delete of doctrine extension but in my case it is not working.

I am using below extension:
[https://github.com/Atlantic18/DoctrineExtensions](https://github.com/Atlantic18/DoctrineExtensions)
In doctrine.yaml:
```
        filters:
            softdeletable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
```
In entity, used annotations for soft-deleting field:
`use Gedmo\Mapping\Annotation as Gedmo;`
```
 * @ORM\Table(name="users")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
```
If currently it does not support extension other than specifically stofdoctrinebundles, how do I store log for soft-deleted item as type "delete" and optionally on restoring soft-deleted item as "restore" in entity audit table with one "deletedAt" field for reference?

**Comment by DamienHarper** [comment]
Hi @hardiksinh, it should work (`Atlantic18/DoctrineExtensions` is the library used by `StofDoctrineExtensionsBundle`).
 
Let's put aside the audit bundle, does the `SoftDeletable` extension work on your system (if you remove a `User` instance and flush, this instance is not deleted but its `deletedAt` field is updated)? 

Also, as long as this problem is different from the topic of this thread (currently closed), could you please open a new issue to discuss further?
