### ISSUE TITLE
ignored_columns work with the property names and not the column names

### ISSUE THREAD

**Issue by Maxdw** [DamienHarper/DoctrineAuditBundle#9]
What I did (as stated in the readme.md):

```
ignored_columns:
    - created_at
    - modified_at
```

What happened:

These columns were not ignored.

What I expected:

For these columns to be ignored.

What I found out:

```
ignored_columns:
    - createdAt
    - modifiedAt
```

Actually worked.

**Comment by DamienHarper** [comment]
@Maxdw you're right, one should use entity properties in the yaml configuration file. 
That's what I meant with the comment **# properties ignored by the audit process** in the README.
To be honest, I was using snake case to name properties (so they were strictly equal to column names) in my sandbox.
It's fixed now in the README on master branch.
