### ISSUE TITLE
Upgrate to latest master (d986e85) removes all audit tables

### ISSUE THREAD

**Issue by n3o77** [DamienHarper/DoctrineAuditBundle#91]
I was on commit cec3178 after you implemented #69 . When I upgraded to d986e85 this morning it will remove all audit tables. Did any configuration change which I need to adjust?

**Comment by DamienHarper** [comment]
@n3o77 sorry for the inconvenience even if it should not have happened. `master` branch is an unstable branch. 
Could you please post (or share with private gist) you current configuration files (`doctrine.yaml`, `dh_doctrine_audit.yaml`)?
Note: you can set composer to use a specific commit for this bundle while I have time to investigate (`composer require damienharper/doctrine-audit-bundle dev-master#cec317872f0c724937bdae5b423befa2c44db6f8`).

**Comment by n3o77** [comment]
no worries, i know master isn't stable so no harm done.

my config is actually very basic

```
dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration
    ignored_columns:
        - createdAt
        - updatedAt

    entities:
        App\Entity\Address: ~
        .... 
```

**Comment by DamienHarper** [comment]
@n3o77 do you use a secondary database to store audits?

**Comment by n3o77** [comment]
no, same db

**Comment by calvera** [comment]
tried to switch to dev-master and all tables are marked for remove in doctrine migration script

**Comment by n3o77** [comment]
@DamienHarper no hurry, i went back to an older version which works fine for me. Thank you very much for all the work.

**Comment by DamienHarper** [comment]
@n3o77 @calvera Could you please try `master` branch and report me any encountered issue?

**Note**: as [mentioned](https://github.com/DamienHarper/DoctrineAuditBundle#creating-and-updating-audit-tables) in the `README.md`, audit tables are created automatically by `doctrine:schema:update` anymore, you have to run `audit:schema:update` to create/update audit schema/tables.

**Comment by n3o77** [comment]
> Note: as mentioned in the README.md, audit tables are not created automatically by doctrine:schema:update anymore, you have to run audit:schema:update to create/update audit schema/tables.

I think this is the issue. We're using doctrine migrations so doctrine doesn't recognize these tables and will drop them in the migration file.

To be precise i'm using the [symfony maker bundle](https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html) and run `bin/console make:migration`.

**Comment by DamienHarper** [comment]
@n3o77 Well, it shouldn't be the case. What options do you pass to `doctrine:schema:update` to get the queries you put in your migrations?
By default, `doctrine:schema:update` only take into consideration tables mapped to entities. So it does not generate `DROP TABLE` queries about other tables (audit tables for example).
It only does so if you pass it the `--complete` option.

**Comment by n3o77** [comment]
I'm executing `bin/console make:migration` which runs `doctrine:migrations:diff` in the background: https://github.com/symfony/maker-bundle/blob/master/src/Maker/MakeMigration.php#L79

**Comment by DamienHarper** [comment]
You’re right, I’ll have a closer look at it ;)

**Comment by calvera** [comment]
i think that the reason for dropping the tables is that migrations drops all other tables than managed by entities

**Comment by DamienHarper** [comment]
@n3o77 @calvera 
Ok, I figured out what's going on: 
- Previously (at the time I used a schema listener), `doctrine:migrations:diff` initially attempted to remove unmapped tables from the schema but the schema listener prevented this by adding them back. Then, Doctrine's schema tool was clever enough to "understand" that doing a `DROP TABLE` then a `CREATE TABLE` was useless so it didn't include all those queries in the generated migration.
- Now (the schema listener is gone), Doctrine's schema tool just keeps the `DROP TABLE` queries in the generated migration.

So, until I find a better way to proceed (if I ever succeed :)), I think I have a quite solid 2 steps workaround: 
1. Make Doctrine ignore audit tables as described in the [documentation](https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#manual-tables). This should make `doctrine:migrations:diff` (so `make:migration`) ignore audit tables so it won't try to remove them. 
```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                schema_filter: ~^.+(?<!_audit)$~  # audit tables are suffixed with "_audit" by default
```
2. Use `audit:schema:update` to generate the audit tables
  - either by running `audit:schema:update --force` which will update create/update audit tables (you can even include this in your deployment tool if you want -- I currently do this with [Deployer](https://deployer.org))
  - or by running `audit:schema:update --dump-sql` which will print the SQL queries to create/update audit tables (you can then copy and paste them in an empty migration file generated by `doctrine:migrations:generate`)

**Comment by n3o77** [comment]
Thanks for looking into that. The issue we will be having with this approach is that we loose the DB downgrade queries in the migration file or would have to create them manually, which even with a relatively small DB is quite time consuming.

It will also add additional steps to remember for every developer when doing a DB change. A common workflow for us is using maker bundles entity command to add a new entity or adding a field / relation to an existing one, then we run `bin/console make:migration` (which is also suggested at the end of the entity command) and if this looks good `bin/console doctrine:migrations:migrate --no-interaction` and we're done. So this requires additional on boarding steps for new devs. In code reviews this requires additional care for the migration scripts. Also deploying needs to be adjusted now.

Please don't understand me wrong, i think your bundle is awesome and the time and effort you put in is amazing and very much appreciated. But this change means for us either staying on an older version or switching back to another solution, which is fine of course, i don't expect you to cater to our needs. Just to give you some background.

**Comment by DamienHarper** [comment]
Thanks for the feedback. 

I understand what you say and do not feel comfortable with this solution too. So be reassured, I won’t release any new major version until I find a real solution. As I said, the above approach is a workaround and should be considered temporary.
I already have an idea on how to solve this. 
Ultimately, the above approach will be only relevant to people using a secondary database to store audits.

**Comment by DamienHarper** [comment]
@n3o77 I just merged some changes that should solve your issues. Feel free to give `master` branch a test and give me some feedback ;)

**Comment by n3o77** [comment]
@DamienHarper again, thank you so much for putting in so much effort. Change looks good to me so far, i'll see how it behaves on my test project the next few days.

**Comment by DamienHarper** [comment]
@n3o77 did you have a chance to try out `master`branch?

**Comment by mklenk** [comment]
I had the same issues and the current master seems to resolve them.
Now `doctrine:migrations:diff` is generating the correct migrations as before. So no more `DROP TABLE` statements and the audit table migrations for my new entities are created as before.

Does this mean that `audit:schema:update` isn't needed anymore?

**Comment by DamienHarper** [comment]
@mklenk thanks for the feedback!
> Does this mean that audit:schema:update isn't needed anymore?

No, `audit:schema:update` command is **still** needed:
- to upgrade your schema if you are upgrading from an older version of the bundle
- if you are using a **dual** database setup (audits are stored in a secondary database -- cf [documentation](https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/doc/20-general-configuration.md#storage-configuration)) 

So, you don't need the `audit:schema:update` command **only if** you're using a **single** database setup (audits are stored in the **same** database than audited entities) **and** you are not upgrading from an older version of the bundle.

**Comment by n3o77** [comment]
@DamienHarper so far everything runs fine for me regarding this isssue. But still need to update to the latest branch with the security annotations to give you feedback on that.

**Comment by DamienHarper** [comment]
@n3o77 thanks for the feedback. Do just checkout `master`, it's already merged into `master`

**Comment by n3o77** [comment]
@DamienHarper i just moved another project to this bundle from the simplethings audit bundle. I'm on commit 4228267 (latest master) and now have the same issue again. It will drop all audit tables instead of updating them. Same config as above.

I assumed that it might be because the tables need to be updated instead of created. But even if remove all the tables before and then run the command the tables won't be created. I'm using the migration command again.

**Comment by n3o77** [comment]
This is on symfony 3.4 not 4.x.

**Comment by n3o77** [comment]
@DamienHarper sorry my mistake. Everything is working as expected.

**Comment by DamienHarper** [comment]
@n3o77 I close this issue for now. Reopen it if needed.
